-- Create the assessments table
create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  hn text not null unique,
  answers jsonb not null, -- JSON structure for questionnaire answers
  result text not null,   -- Assessment result text
  scores jsonb not null   -- JSON structure for grouping scores
);

-- Enable Row Level Security (RLS)
alter table public.assessments enable row level security;

-- Create policies (Optional if using Service Role Key exclusively, but good for future-proofing)
create policy "Enable read access for all users" on public.assessments for select using (true);
create policy "Enable insert for all users" on public.assessments for insert with check (true);
create policy "Enable update for all users" on public.assessments for update using (true);

-- Create an index on HN
create index if not exists assessments_hn_idx on public.assessments (hn);

alter table public.assessments disable row level security;
