-- Create the assessments table
create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  hn text not null unique,
  answers jsonb not null, -- JSON structure for questionnaire answers
  result text not null,   -- Assessment result text
  scores jsonb not null   -- JSON structure for grouping scores
);

-- Enable Row Level Security (RLS)
alter table public.assessments enable row level security;

-- Create policies (Optional if using Service Role Key exclusively, but good for future-proofing)
create policy "Enable read access for all users" on public.assessments for select using (true);
create policy "Enable insert for all users" on public.assessments for insert with check (true);
create policy "Enable update for all users" on public.assessments for update using (true);

-- Create an index on HN
create index if not exists assessments_hn_idx on public.assessments (hn);

alter table public.assessments disable row level security;

-- Create the assessment history table (supports multiple assessments per HN)
create table if not exists public.assessment_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  hn text not null,
  assessment_no integer not null, -- 1,2,3... for each HN (auto-generated by trigger if omitted)
  assessment_date timestamp with time zone default timezone('utc'::text, now()) not null,
  result text not null,            -- Result for this specific assessment
  answers jsonb not null,          -- Snapshot of questionnaire answers for this assessment
  scores jsonb not null,           -- Snapshot of grouped scores for this assessment
  note text,                       -- Optional notes for this assessment
  constraint assessment_history_assessment_no_check check (assessment_no > 0),
  constraint assessment_history_hn_no_unique unique (hn, assessment_no)
);

-- Auto-generate assessment_no per HN when not provided
create or replace function public.set_assessment_history_no()
returns trigger
language plpgsql
as $$
begin
  if new.assessment_no is null then
    select coalesce(max(assessment_no), 0) + 1
      into new.assessment_no
      from public.assessment_history
     where hn = new.hn;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_assessment_history_set_no on public.assessment_history;
create trigger trg_assessment_history_set_no
before insert on public.assessment_history
for each row
execute function public.set_assessment_history_no();

-- Enable Row Level Security (RLS)
alter table public.assessment_history enable row level security;

-- Create policies (Optional if using Service Role Key exclusively, but good for future-proofing)
create policy "Enable read access for all users" on public.assessment_history for select using (true);
create policy "Enable insert for all users" on public.assessment_history for insert with check (true);
create policy "Enable update for all users" on public.assessment_history for update using (true);

-- Create indexes for common history queries
create index if not exists assessment_history_hn_idx on public.assessment_history (hn);
create index if not exists assessment_history_hn_date_idx on public.assessment_history (hn, assessment_date desc);

alter table public.assessment_history disable row level security;
